package ke.co.neatline.brookemapper.models

data class AgrovetMonitoringBody(
   val Name:String,
   val Longitude: Double,
   val Latitude: Double,
   val Country: String,
   val County: String,
   val Town: String,
   val Unit: String,
   val Location: String,
   val Date: String,
   val Quater: String,
   val Project: String,
   val Education:String,
   val Profession: String,
   val Registration: String,
   val Premises: String,
   val Pest: String,
   val Labelling: String,
   val Dispense:String,
   val Vital: String,
   val History: String,
   val DecisionMaking: String,
   val Prevention: String,
   val Effects: String,
   val Referral: String,
   val FollowUp: String,
   val Conduct: String,
   val PainRecognition:String,
   val Findings: String,
   val ProblemCause: String,
   val RationalTreatment: String,
   val DoseCalculation: String,
   val RouteOfAdministration: String,
   val OwnerExplanation: String,
   val Steroids: String,
   val EyePreparation: String,
   val Dewormers: String,
   val Antiseptic: String,
   val SyntheticPyrethoids: String,
   val PainRelief: String,
   val InjectableAntibiotic: String,
   val OralAntibiotic: String,
   val WelfareProducts: String,
   val MedicineStorage: String,
   val EquipmentDisposables: String,
   val ProductDisplay: String,
   val AppropriateWastes: String,
   val RecordKeeping: String
)