package ke.co.neatline.brookemapper.models

data class AgrovetMonitoringBody(
   val Name:String,
   val Longitude: Double,
   val Latitude: Double,
   val Country: String,
   val County: String,
   val Town: String,
   val Unit: String,
   val Location: String,
   val Date: String,
   val Quater: String,
   val Project: String,
   val Education:String,
   val Registration: String,
   val Premises: String,
   val Pest: String,
   val Labelling: String,
   val Dispense:String,
   val Vital: String,
   val History: String,
   val DecisionMaking: String,
   val Prevention: String,
   val Effects: String,
   val Referral: String,
   val FollowUp: String,
   val Conduct: String,
   val recognition:String,
   val findings: String,
   val problemcause: String,
   val rationaltreatment: String,
   val dosecalculation: String,
   val sideeffects: String,
   val routeadministration: String,
   val ownerexplanation: String,
   val steroids: String,
   val eyepreparation: String,
   val dewormers: String,
   val antiseptic: String,
   val pyrethroids: String,
   val painrelief: String,
   val injectableantibiotic: String,
   val oralantibiotic: String,
   val welfareproducts: String,
   val medicinestorage: String,
   val equipmentdisposable: String,
   val productdisplay: String,
   val appropriatewastes: String,
   val recordkeeping: String
)