package ke.co.neatline.brookemapper.models

data class AgrovetMonitoringGetBody(
   val ID:String,
   val Name:String,
   val Longitude: Double,
   val Latitude: Double,
   val Country: String,
   val County: String,
   val Town: String,
   val Unit: String,
   val Location: String,
   val Date: String,
   val Quater: String,
   val Project: String,
   val Education:String,
   val Profession:String,
   val Registration: String,
   val Premises: String,
   val Pest: String,
   val Labelling: String,
   val Dispense:String,
   val Vital: String,
   val History: String,
   val DecisionMaking: String,
   val Prevention: String,
   val Effects: String,
   val Referral: String,
   val FollowUp: String,
   val Conduct: String,
)